// GENERATED by `npm run db:pull` — introspected FROM the live schema.
//
// This describes the database; it does not define it. `migrations/` is the
// only thing that changes the schema, and `store.d1.ts` is the only file the
// Worker runs queries from. Nothing here is imported by the Worker.
//
// It exists so Drizzle Studio has something to render. If it disagrees with
// the database, re-pull it — do not edit it and do not migrate from it.
import { sqliteTable, AnySQLiteColumn, index, text, real, integer, primaryKey, numeric, foreignKey } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const events = sqliteTable("events", {
	id: text().primaryKey(),
	kind: text().notNull(),
	nameEn: text("name_en").notNull(),
	nameHi: text("name_hi").notNull(),
	dateFrom: text("date_from").notNull(),
	dateTo: text("date_to").notNull(),
	places: text().default("[]").notNull(),
	visitFactor: real("visit_factor").default(1).notNull(),
	travelFactor: real("travel_factor").default(1).notNull(),
	blurbEn: text("blurb_en").notNull(),
	blurbHi: text("blurb_hi").notNull(),
	noticeEn: text("notice_en").notNull(),
	noticeHi: text("notice_hi").notNull(),
	bias: text(),
	img: text(),
	winFrom: text("win_from"),
	winTo: text("win_to"),
	corridor: text(),
	advice: text(),
	updatedAt: integer("updated_at").notNull(),
},
(table) => [
	index("events_dates").on(table.dateFrom, table.dateTo),
	index("events_updated").on(table.updatedAt),
]);

export const subs = sqliteTable("subs", {
	endpoint: text().primaryKey(),
	p256Dh: text().notNull(),
	auth: text().notNull(),
	lang: text().default("en").notNull(),
	createdAt: integer("created_at").notNull(),
});

export const sent = sqliteTable("sent", {
	eventId: text("event_id").notNull(),
	day: text().notNull(),
	at: integer().notNull(),
},
(table) => [
	primaryKey({ columns: [table.eventId, table.day], name: "sent_event_id_day_pk"})
]);

export const audit = sqliteTable("audit", {
	id: integer().primaryKey({ autoIncrement: true }),
	at: integer().notNull(),
	who: text().notNull(),
	action: text().notNull(),
	entity: text().notNull(),
	entityId: text("entity_id").notNull(),
	after: text(),
},
(table) => [
	index("audit_at").on(table.at),
]);

export const d1Migrations = sqliteTable("d1_migrations", {
	id: integer().primaryKey({ autoIncrement: true }),
	name: text(),
	appliedAt: numeric("applied_at").default(sql`(CURRENT_TIMESTAMP)`).notNull(),
});

export const content = sqliteTable("content", {
	kind: text().notNull(),
	id: text().notNull(),
	doc: text().notNull(),
	updatedAt: integer("updated_at").notNull(),
},
(table) => [
	index("content_kind").on(table.kind, table.updatedAt),
	primaryKey({ columns: [table.kind, table.id], name: "content_kind_id_pk"})
]);

export const user = sqliteTable("user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer().notNull(),
	image: text(),
	createdAt: numeric().notNull(),
	updatedAt: numeric().notNull(),
	role: text(),
});

export const session = sqliteTable("session", {
	id: text().primaryKey().notNull(),
	expiresAt: numeric().notNull(),
	token: text().notNull(),
	createdAt: numeric().notNull(),
	updatedAt: numeric().notNull(),
	ipAddress: text(),
	userAgent: text(),
	userId: text().notNull().references(() => user.id, { onDelete: "cascade" } ),
},
(table) => [
	index("session_userId_idx").on(table.userId),
]);

export const account = sqliteTable("account", {
	id: text().primaryKey().notNull(),
	accountId: text().notNull(),
	providerId: text().notNull(),
	userId: text().notNull().references(() => user.id, { onDelete: "cascade" } ),
	accessToken: text(),
	refreshToken: text(),
	idToken: text(),
	accessTokenExpiresAt: numeric(),
	refreshTokenExpiresAt: numeric(),
	scope: text(),
	password: text(),
	createdAt: numeric().notNull(),
	updatedAt: numeric().notNull(),
},
(table) => [
	index("account_userId_idx").on(table.userId),
]);

export const verification = sqliteTable("verification", {
	id: text().primaryKey().notNull(),
	identifier: text().notNull(),
	value: text().notNull(),
	expiresAt: numeric().notNull(),
	createdAt: numeric().notNull(),
	updatedAt: numeric().notNull(),
},
(table) => [
	index("verification_identifier_idx").on(table.identifier),
]);

export const rateLimit = sqliteTable("rateLimit", {
	id: text().primaryKey().notNull(),
	key: text().notNull(),
	count: integer().notNull(),
	lastRequest: integer().notNull(),
});

