-- Rate-limit counters for Better Auth.
--
-- GENERATED by @better-auth/cli alongside the rest of the auth schema; only
-- the new table is kept here, because 0003 already created the others and a
-- migration must be safe to run exactly once, in order.
--
-- In D1 rather than memory on purpose: Workers requests land on whichever
-- isolate is free, so an in-memory counter gives an attacker a fresh allowance
-- on every request and the limit never bites. See src/auth.ts.
create table "rateLimit" (
  "id"          text not null primary key,
  "key"         text not null unique,
  "count"       integer not null,
  "lastRequest" bigint not null
);
