-- Kurukshetra Saarthi — content and push schema. Postgres.
--
-- Carried over from the D1/SQLite original (migrations/0001_init.sql) with the
-- types corrected rather than the design. The variable-shaped parts of an event
-- (places, bias, corridor) stay JSON text rather than child tables: they are
-- always read and written as a whole event and never queried across, so
-- normalising would buy joins nobody performs and cost a migration every time
-- the shape gains a field.
--
-- Why text and not jsonb, now that Postgres offers it: the Worker stores and
-- returns these strings verbatim and never queries inside them. jsonb would
-- reparse and re-serialise on every read, and — the part that would actually
-- bite — it does not preserve key order or duplicate keys, so what came back
-- would not be byte-identical to what the admin saved. Move a field to jsonb
-- when something needs to query it, not before.

CREATE TABLE IF NOT EXISTS events (
  id            text PRIMARY KEY,
  kind          text NOT NULL,
  name_en       text NOT NULL,
  name_hi       text NOT NULL,
  date_from     text NOT NULL,                    -- ISO yyyy-mm-dd, inclusive
  date_to       text NOT NULL,                    -- inclusive; same as from for one day
  places        text NOT NULL DEFAULT '[]',
  visit_factor  double precision NOT NULL DEFAULT 1,
  travel_factor double precision NOT NULL DEFAULT 1,
  blurb_en      text NOT NULL,
  blurb_hi      text NOT NULL,
  notice_en     text NOT NULL,
  notice_hi     text NOT NULL,
  bias          text,
  img           text,
  win_from      text,                             -- HH:MM; overlays only
  win_to        text,
  corridor      text,                             -- JSON [{lat,lng}]; overlays only
  advice        text,                             -- 'join' | 'avoid'
  -- Epoch milliseconds, so bigint. int4 tops out at 2.1e9 and a millisecond
  -- timestamp passed 1.7e12 years ago — this is the one type SQLite let us be
  -- careless about and Postgres will not.
  updated_at    bigint NOT NULL
);

-- the app asks "what changed" far more often than "what is on"
CREATE INDEX IF NOT EXISTS events_updated ON events (updated_at);
CREATE INDEX IF NOT EXISTS events_dates   ON events (date_from, date_to);

-- One row per browser that asked to be told. The endpoint URL is unique per
-- browser installation, so it is the natural key — no id of our own to keep in
-- step, and a re-subscribe overwrites rather than duplicates.
CREATE TABLE IF NOT EXISTS subs (
  endpoint   text PRIMARY KEY,
  p256dh     text NOT NULL,
  auth       text NOT NULL,
  lang       text NOT NULL DEFAULT 'en',
  created_at bigint NOT NULL
);

-- What has already been pushed. The cron runs every quarter hour and must be
-- able to run twice without telling anyone twice; this is what makes it
-- idempotent. Keyed by (event, day) because an annual event recurs.
CREATE TABLE IF NOT EXISTS sent (
  event_id text NOT NULL,
  day      text NOT NULL,
  at       bigint NOT NULL,
  PRIMARY KEY (event_id, day)
);

-- Who changed what. Management is several people sharing a login; the first
-- time a date changes and nobody remembers changing it, this is the only
-- question anyone will ask. `after` holds the whole row, so a bad edit is
-- recoverable by reading it back out.
--
-- `GENERATED … AS IDENTITY` is the Postgres spelling of SQLite's INTEGER
-- PRIMARY KEY AUTOINCREMENT. `BY DEFAULT` rather than `ALWAYS` so the copy from
-- D1 can keep the ids the rows already have. A sequence does not notice ids
-- inserted past it, so `db/copy-from-d1.mjs` resets it when the copy is done —
-- without that, the next audit entry written by the Worker collides with a
-- copied row and the insert fails.
CREATE TABLE IF NOT EXISTS audit (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at        bigint NOT NULL,
  who       text NOT NULL,
  action    text NOT NULL,
  entity    text NOT NULL,
  entity_id text NOT NULL,
  after     text
);
CREATE INDEX IF NOT EXISTS audit_at ON audit (at DESC);
