import edgeData from "@/content/data/edges.json";

/**
 * The place graph — what a straight line between two coordinates cannot say.
 *
 * Source of truth: src/content/data/edges.json, generated by
 * `npm run build-graph` from the coordinates in destinations.json and
 * places-index.json, then corrected by hand. See docs/10 §4.3.
 *
 * Two relationships, and the difference matters:
 *
 *   same-complex  one gate, one car park, usually one wall. The Gurudwara on
 *                 the Brahma Sarovar embankment is 7m from the sarovar. These
 *                 form clusters, and a cluster pays for parking once.
 *
 *   walkable      far enough to need the decision, near enough to make it —
 *                 you leave the car where it is and walk. NOT transitive: A is
 *                 walkable to B and B to C does not put A and C in one pocket,
 *                 or the whole of central Kurukshetra becomes a single stop
 *                 you can supposedly cover on foot. 126 of the 630 destination
 *                 pairs are within 900m of each other; transitive closure over
 *                 those is a 3km "walk".
 */
export type Rel = "same-complex" | "walkable";

export interface Edge {
  a: string;
  b: string;
  rel: Rel;
  /** straight-line metres between the two pins */
  m: number;
  min: { walking: number; [mode: string]: number };
  /** true once a person has actually walked it — see docs/10 §4.3 */
  verified?: boolean;
  note?: { en: string; hi: string };
}

export const EDGES = edgeData as unknown as Edge[];

const key = (a: string, b: string) => (a < b ? a + "|" + b : b + "|" + a);

const byKey = new Map<string, Edge>();
const neighbours = new Map<string, Edge[]>();
for (const e of EDGES) {
  byKey.set(key(e.a, e.b), e);
  for (const id of [e.a, e.b]) {
    const list = neighbours.get(id);
    if (list) list.push(e);
    else neighbours.set(id, [e]);
  }
}

/** The edge between two places, if they have one. */
export const edge = (a: string, b: string): Edge | undefined => byKey.get(key(a, b));

/** Every place directly joined to this one, with the edge that joins them. */
export const linked = (id: string): { id: string; e: Edge }[] =>
  (neighbours.get(id) || []).map((e) => ({ id: e.a === id ? e.b : e.a, e }));

/** Minutes on foot between two joined places, or undefined if they aren't joined. */
export const walkMin = (a: string, b: string): number | undefined => edge(a, b)?.min.walking;

/**
 * Can you leave the car where it is and walk to the other one?
 *
 * True for both relationships: same-complex is the strong case, walkable the
 * ordinary one. The scheduler uses this to decide whether a second stop costs
 * a second parking buffer, which is the whole point of the file.
 */
export const onFoot = (a: string, b: string): boolean => !!edge(a, b);

/* ---- clusters: connected components over same-complex edges ONLY ---- */
const clusterOf = new Map<string, string>();
{
  const parent = new Map<string, string>();
  const find = (x: string): string => {
    let r = x;
    while (parent.get(r) && parent.get(r) !== r) r = parent.get(r)!;
    return r;
  };
  for (const e of EDGES) {
    if (e.rel !== "same-complex") continue;
    if (!parent.has(e.a)) parent.set(e.a, e.a);
    if (!parent.has(e.b)) parent.set(e.b, e.b);
    const ra = find(e.a),
      rb = find(e.b);
    if (ra !== rb) parent.set(ra, rb);
  }
  for (const id of parent.keys()) clusterOf.set(id, find(id));
}

/** The cluster this place belongs to, or its own id when it stands alone. */
export const cluster = (id: string): string => clusterOf.get(id) || id;

/** Do these two share one gate and one car park? */
export const sameComplex = (a: string, b: string): boolean => a !== b && cluster(a) === cluster(b);
