/// <reference types="node" />
// This file runs under Node (drizzle-kit), not in the Worker. The Worker's
// tsconfig types it as workers-only, which is correct for src/ and wrong here
// — hence the reference above, rather than adding "node" to the whole project
// and letting Worker code reach for process.env that will not exist at runtime.
import { defineConfig } from "drizzle-kit";

/**
 * Drizzle Studio — a BROWSER for the database, not the app's data layer.
 *
 * This is the one thing the Cloudflare dashboard's D1 console is bad at:
 * looking at rows. Studio gives a real table view, filtering and inline edits.
 *
 * What it deliberately is NOT: `store.d1.ts` still holds every query the
 * Worker runs, and `migrations/` is still the only thing that changes the
 * schema. Nothing here is imported by the Worker, and `drizzle/schema.ts` is
 * generated by introspection — so it follows the database rather than
 * defining it, and cannot drift into being a second source of truth.
 *
 *   npm run db          browse the LOCAL database — no credentials needed
 *   npm run db:remote   browse PRODUCTION — needs a token, see below
 *
 * For remote, create a Cloudflare API token (My Profile → API Tokens) with
 * Account → D1 → Edit, restricted to this account, then:
 *
 *   export CLOUDFLARE_ACCOUNT_ID=4768790aa47814f60dd70c187c7a7bd9
 *   export CLOUDFLARE_D1_TOKEN=…
 *
 * That token is a password for the client's database. Never commit it, and
 * prefer the local view for anything that does not need production rows.
 */
const remote = process.env.D1_REMOTE === "1";

export default defineConfig(
  remote
    ? {
        dialect: "sqlite",
        driver: "d1-http",
        schema: "./drizzle/schema.ts",
        out: "./drizzle",
        dbCredentials: {
          accountId: process.env.CLOUDFLARE_ACCOUNT_ID!,
          databaseId: "43389d66-b722-40bc-ae9f-ea5c194a6edf",
          token: process.env.CLOUDFLARE_D1_TOKEN!,
        },
      }
    : {
        dialect: "sqlite",
        schema: "./drizzle/schema.ts",
        out: "./drizzle",
        // wrangler names the local file after a hash of the binding, so it is
        // resolved at run time rather than written down and going stale.
        dbCredentials: { url: process.env.LOCAL_D1_PATH || "" },
      },
);
