// Load the bundled JSON into D1's `content` table.
//
// The app ships a complete copy of its data and always will — that is what
// makes it work on a dead signal. This script makes the database agree with
// that copy, so the endpoint and the fallback start life identical and the
// Board edits forward from there.
//
// It writes SQL to stdout rather than talking to D1 itself, because wrangler
// already knows how to run a file against local or remote and reimplementing
// that here would mean holding credentials in a script nobody audits:
//
//   node import-content.mjs > /tmp/content.sql
//   npx wrangler d1 execute discover_kurukshetra --remote --file=/tmp/content.sql
//
// Or just `npm run import` / `npm run import:local`.
//
// Re-running is safe: every statement is an upsert keyed on (kind, id). It
// does NOT delete rows that have vanished from the JSON — a script that can
// silently empty the live catalogue because someone mistyped a filename is a
// worse failure than a stale row. Deletions go through the dashboard.
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const DATA = join(HERE, "..", "web", "src", "content", "data");

/** content kind → the bundled file it mirrors. Must match CONTENT_KINDS. */
const FEEDS = {
  places: "destinations.json",
  startpoints: "places-index.json",
  hotels: "hotels.json",
  erickshaw: "erickshaw.json",
  hero: "hero.json",
};

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";

let statements = 0;
const out = [];
out.push("-- generated by apps/api/import-content.mjs — do not edit by hand");

for (const [kind, file] of Object.entries(FEEDS)) {
  const path = join(DATA, file);
  if (!existsSync(path)) {
    console.error(`skip ${kind}: ${file} does not exist yet`);
    continue;
  }

  const items = JSON.parse(readFileSync(path, "utf8"));
  if (!Array.isArray(items)) throw new Error(`${file} is not an array`);

  const seen = new Set();
  for (const item of items) {
    if (!item?.id) throw new Error(`${file}: an item has no id`);
    // A duplicate id would silently become one row and lose a place. Loud here
    // beats a catalogue that is quietly one short.
    if (seen.has(item.id)) throw new Error(`${file}: duplicate id ${item.id}`);
    seen.add(item.id);

    out.push(
      `INSERT INTO content (kind, id, doc, updated_at) VALUES (${q(kind)}, ${q(item.id)}, ${q(
        JSON.stringify(item),
      )}, ${Date.now()}) ON CONFLICT(kind, id) DO UPDATE SET doc=excluded.doc, updated_at=excluded.updated_at;`,
    );
    statements++;
  }
  console.error(`${kind}: ${items.length} items from ${file}`);
}

if (!statements) {
  console.error("nothing to import");
  process.exit(1);
}

console.log(out.join("\n"));
console.error(`${statements} statements written`);
